<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Fájlok feltöltése és képátméretezés</title>
  <link rel="stylesheet" href="/learn_php_advanced/6.File_upload/server//public/css/bootstrap.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>


<body>
  <div class="container">
    <div class="p-4 mb-4 bg-light rounded-3">
      <div class="container">
        <h1 class="display-5 fw-bold">Fájlok feltöltése</h1>
        <p class="lead">És képátméretezés (kicsi, közepes, nagy)</p>
      </div>
    </div>

    <?php if ($params['isSuccess'] ?? false) : ?>
      <div class="alert alert-success text-center m-2">
        Feltöltés sikeres
        <i class="fa fa-check-circle"> </i>
      </div>
    <?php endif; ?>

    <form action="/learn_php_advanced/6.File_upload/server/upload-images" method="POST" enctype="multipart/form-data">
      <div class="form-row">
        <div class="mb-3">
          <input type="file" name="fajlok[]" multiple class="form-control" placeholder="Fájlok" />
        </div>
      </div>

      <button class="btn btn-primary" type="submit">Küldés</button>
    </form>

    <hr>
    <div class="row">
      <?php foreach ($params['images'] ?? [] as $image) : ?>
        <div class="col-4 d-inline-block text-center mb-2">
          <img class="img-fluid img-thumbnail" src="/learn_php_advanced/6.File_upload/server/public/images/<?= $image['name'] ?>.<?= $image["type"] ?>" alt="">
        </div>
      <?php endforeach; ?>
    </div>

  </div>
</body>

</html>