<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Form validáció</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" integrity="sha512-usVBAd66/NpVNfBge19gws2j6JZinnca12rAe2l+d+QkLU9fiG02O1X8Q6hepIpr/EYKZvKx/I9WsnujJuOmBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>


<body>
  <div class="container">
    <div class="p-4 mb-4 bg-light rounded-3">
      <div class="container">
        <h1 class="display-5 fw-bold">Form validáció</h1>
        <p class="lead">Példa: Új alkalmazott</p>
      </div>
    </div>

    <?php if ($params['isSuccess']) : ?>
      <div class="alert alert-success text-center m-2">
        <i class="fa fa-check-circle display-1"> </i>
      </div>
    <?php endif; ?>

    <form action="/new-employee" method="POST" class="m-2">
      <div class="form-row">
        <div class="mb-3">
          Név:
          <input type="text" name="name" class="form-control" placeholder="Név" />
          <div class="invalid-feedback">

          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="mb-3">
          Szerepkör:
          <select class="custom-select form-control" name="role">
            <option value="worker" <?= ($params['values']['role'] ?? '') === "worker" ? 'selected' : '' ?>>Dolgozó</option>
            <option value="manager" <?= ($params['values']['role'] ?? '') === "manager" ? 'selected' : '' ?>>Menedzser</option>
            <option value="leader" <?= ($params['values']['role'] ?? '') === "leader" ? 'selected' : '' ?>>Vezető</option>
          </select>
          <div class="invalid-feedback">

          </div>
        </div>

        <div class="mb-3">
          Életkor
          <input type="number" name="age" class="form-control" placeholder="Életkor" />
          <div class="invalid-feedback">

          </div>
        </div>

        <div class="mb-3">
          Munkabér:
          <input type="text" class="form-control" name="salary" placeholder="Munkabér" />
          <div class="invalid-feedback">

          </div>
        </div>
      </div>
      <div class="mb-3">
        Email (opcionális):
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">@</span>
          </div>
          <input type="text" class="form-control" placeholder="Email" name="email" />

          <div class="invalid-feedback">

          </div>
        </div>
      </div>
      <div class="form-group mb-2">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" name="isVerified" />
          <label class="form-check-label">Elfogadom a felhasználói feltételeket</label>
          <div class="invalid-feedback">

          </div>
        </div>
      </div>

      <button class="btn btn-primary" type="submit">Küldés</button>
    </form>
  </div>
</body>

</html>