<div class="mb-3 content-body">
  <div class="col-sm-12">
    <div class="card p-3">
      <div class="card-body">
        <div class="card-title">
          <h1 class="mb-4 mt-5 text-center">Oldal nem található!</h1>

        </div>
        <div class="card-body m-auto text-center">
          <a href="/" class="m-auto">
            <button class="btn btn-primary">Kezdőlap</button>
          </a>
        </div>

      </div>
    </div>
  </div>
</div>
