<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Form validáció</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" integrity="sha512-usVBAd66/NpVNfBge19gws2j6JZinnca12rAe2l+d+QkLU9fiG02O1X8Q6hepIpr/EYKZvKx/I9WsnujJuOmBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
  <?php

  $isValidClass = function ($key) use ($params) {
    if (!$params['errorMessages']) {
      return "";
    }
    return count($params['errorMessages'][$key] ?? []) ? "is-invalid" : "is-valid";
  };
  ?>
  <div class="container">
    <div class="p-4 mb-4 bg-light rounded-3">
      <div class="container">
        <h1 class="display-5 fw-bold">Form validáció</h1>
        <p class="lead">Példa: Új alkalmazott</p>
      </div>
    </div>

    <?php if ($params['isSuccess']) : ?>
      <div class="alert alert-success text-center m-2">
        <i class="fa fa-check-circle display-1"> </i>
      </div>
    <?php endif; ?>

    <form action="/new-employee" method="POST" class="m-2">
      <div class="form-row">
        <div class="mb-3">
          Név:
          <input type="text" name="name" value="<?= $params['values']['name'] ?? '' ?>" class="form-control <?= $isValidClass('name') ?>" placeholder="Név" />
          <div class="invalid-feedback">
            <?php foreach ($params['errorMessages']['name'] as $error) : ?>
              <?= $error ?> <br />
            <?php endforeach; ?>
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="mb-3">
          Szerepkör:
          <select class="custom-select form-control <?= $isValidClass('role') ?> " name="role">
            <option value="worker" <?= ($params['values']['role'] ?? '') === "worker" ? 'selected' : '' ?>>Dolgozó</option>
            <option value="manager" <?= ($params['values']['role'] ?? '') === "manager" ? 'selected' : '' ?>>Menedzser</option>
            <option value="leader" <?= ($params['values']['role'] ?? '') === "leader" ? 'selected' : '' ?>>Vezető</option>
          </select>
          <div class="invalid-feedback">
            <?php foreach ($params['errorMessages']['role'] as $error) : ?>
              <?= $error ?> <br />
            <?php endforeach; ?>
          </div>
        </div>
        <div class="mb-3">
          Életkor
          <input type="number" name="age" value="<?= $params['values']['age'] ?? '' ?>" class="form-control <?= $isValidClass('age') ?>" placeholder="Életkor" />
          <div class="invalid-feedback">
            <?php foreach ($params['errorMessages']['age'] as $error) : ?>
              <?= $error ?> <br />
            <?php endforeach; ?>
          </div>
        </div>

        <div class="mb-3">
          Munkabér:
          <input type="text" class="form-control <?= $isValidClass('salary') ?>" name="salary" value="<?= $params['values']['salary'] ?? '' ?>" placeholder="Munkabér" />

          <div class="invalid-feedback">
            <?php foreach ($params['errorMessages']['salary'] as $error) : ?>
              <?= $error ?> <br />
            <?php endforeach; ?>
          </div>
        </div>
      </div>
      <div class="mb-3">
        Email (opcionális):
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">@</span>
          </div>
          <input type="text" class="form-control <?= $isValidClass('email') ?>" placeholder="Email" name="email" value="<?= $params['values']['email'] ?? '' ?>" />

          <div class="invalid-feedback">
            <?php foreach ($params['errorMessages']['email'] as $error) : ?>
              <?= $error ?> <br />
            <?php endforeach; ?>
          </div>
        </div>
      </div>
      <div class="form-group mb-2">
        <div class="form-check">
          <input class="form-check-input <?= $isValidClass('isVerified') ?>" type="checkbox" name="isVerified" <?= $params['values']['isVerified'] ?? '' ? 'checked' : '' ?> />
          <label class="form-check-label">Elfogadom a felhasználói feltételeket</label>

          <div class="invalid-feedback">
            <?php foreach ($params['errorMessages']['isVerified'] as $error) : ?>
              <?= $error ?> <br />
            <?php endforeach; ?>
          </div>
        </div>
      </div>

      <button class="btn btn-primary" type="submit">Küldés</button>
    </form>
  </div>
</body>

</html>